### ISSUE TITLE
vir smear correction saturation indexing

### ISSUE THREAD

**Issue by geomorphlab** [AStcherbinine/omegapy#11]
https://github.com/AStcherbinine/omegapy/blob/24193ba2a787cc264085a72e006233dd8e8d415d/omegapy/omega_data.py#L586

Could you please check if this is definitely working as intended? I think potentially when `i_sat` is used to index `vis_tmp` it is actually zeroing out the wrong bands (since `i_sat` is found on Line 585 using `vis_tmp[85:]` not `vis_tmp`). Also, why 85 when comment on Line 592 says 90:95? Great package - thanks.

**Comment by AStcherbinine** [comment]
Thanks for pointing that!
Indeed it was zeroing the wrong wavelengths, it has been fixed with commit 4e2720d894affd95351be626946c33a751fa6507

https://github.com/AStcherbinine/omegapy/blob/dbb973c2548007634f0b6b395fd8b79c6086b1d5/omegapy/omega_data.py#L582-L590

And regarding the 90 vs 85 in the comment, it is a typo from the IDL file that has not been fixed when porting to Python, now corrected.

**Comment by geomorphlab** [comment]
Thanks Aurélien. I have made some efficiency improvements in my local version of your code (e.g., getting rid of all loops in _readomega) - I will share these with you soon but maybe it's no longer a faithful translation of the IDL code.
