### ISSUE TITLE
Add IDL Routines as a Citation instead of a hyperlink

### ISSUE THREAD

**Issue by Sierra-MC** [AStcherbinine/omegapy#7]
Use a citation (which can include the url) instead of solely a url for the IDL Routines.

Review requirement: References: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax](https://pandoc.org/MANUAL.html#extension-citations)?

openjournals/joss-reviews#6566

**Comment by AStcherbinine** [comment]
Thank you for pointing that.
A reference has been added in the paper instead of the sole link for the SOFT10 with commit 09c998d1fdddcc9fc9815c3f41a3958818f5952f

Updated by editorialbot:
👉📄 [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.06566/joss.06566/10.21105.joss.06566.pdf) 📄 [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.06566/joss.06566/10.21105.joss.06566.pdf) 📄 👈

**Comment by Sierra-MC** [comment]
Awesome, looking good!
